version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cijfer_generator_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cijfer_generator
      POSTGRES_USER: cijfer_user
      POSTGRES_PASSWORD: cijfer_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cijfer_user -d cijfer_generator"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cijfer_generator_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - pgadmin

volumes:
  postgres_data:
